Add pkce cusom headers
auth0/Auth0.Android pull request #351
Opened 2020-09-22 12:41 UTC by TLFilip

### Changes

For security reasons we need an option to add custom headers for token request. Such a possibility exists for email/password authentication and refresh token. This PR enables it for social login by adding `WebAuthProvider.Builder` method `withHeaders`.

### Testing

To test it inspect the network traffic and notice custom headers in token request when executing OAuth2 flow.

- [x] This change adds unit test coverage

- [x] This change adds integration test coverage

- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [x] All existing and new tests complete without errors

2020-10-01 10:02 UTC, TLFilip commented
Hey, let me know if there’s a chance to merge that PR and what is required to do so. Thanks!

2020-10-19 16:08 UTC, danielphillips commented
@cocojoe  Hi Martin, as discussed a while ago, could you look into this PR please?

2020-10-19 20:05 UTC, lbalmaceda commented
Apologies for missing this one. I might be able to take a look next week. I'm tracking this internally under `SDK-2080`.

2020-12-15 09:10 UTC, lbalmaceda requested changes
Hey @TLFilip, sorry for the time it took us to review this. We're currently working on the next major and making some improvements (this included). We hope to deliver that soon.

That said, I think makes sense to have this in the current major before that new one is shipped. The PR looks good. I've left a change request to refactor a bit of the methods, especially given that most of the classes there are package private.

2020-12-15 09:10 UTC, lbalmaceda commented on auth0/src/main/java/com/auth0/android/provider/OAuthManager.java
> +    private void addPKCEHeaders(@NonNull Map<String, String> httpHeaders) {
I'd merge this method into `addPKCEParameters`. Please, make the `createPKCE()` method take the headers in addition to the redirectUri. That way they are passed in the construction of the PKCE instance. That would as well remove the setter (pkce.setHeaders)

2020-12-15 13:44 UTC, lbalmaceda approved these changes

2020-12-15 13:44 UTC, merged

2020-12-15 13:44 UTC, lbalmaceda commented
Thanks for the changes @TLFilip