Proper migration for the new key sets was applied.
auth0/Auth0.Android pull request #481
Opened 2021-05-18 23:56 UTC by Maksym-Motornyi

### Changes

Proper migration from to version 1.24+ was applied. This [commit](https://github.com/auth0/Auth0.Android/commit/0a259f11397aa2b4a3fa17e27802598f47642ecc) contains "fix" that makes user force logout without any reason. So I applied proper fix to keep existing users being logged in after the upgrade for any version before 1.24. 

### References

This PR will actually fix the problem described here: https://github.com/auth0/Auth0.Android/issues/324 while https://github.com/auth0/Auth0.Android/pull/325 actually do nothing valuable to avoid the logout problem.

### Testing

1. Install 1.23.0 app.
2. Log in.
3. Install app from current branch.
4. See that user is still logged in.

I didn't add unit tests yet since I don't know if library maintainers would be pleased with my contribute. So let me know if I should add some to complete the PR.

- [ ] This change adds unit test coverage

- [ ] This change adds integration test coverage

- [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)

- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)

- [ ] All existing and new tests complete without errors

2021-05-19 08:44 UTC, Maksym-Motornyi commented
@lbalmaceda Please let me know what you think regarding to this PR.

2021-05-19 09:18 UTC, serhiimakarenkonewscouk commented on auth0/src/main/java/com/auth0/android/authentication/storage/CryptoUtil.java
> +                }
what if existing key is null??

2021-06-04 18:07 UTC, lbalmaceda requested changes
Apologies for the delay in getting back to you. I made a quick pass and the changes look good to me. Would you add the unit tests for the fallback logic from the `CryptoUtil` class, please? I can clone the PR and test this manually the next week. Cheers

2021-07-23 13:12 UTC, Maksym-Motornyi commented
Our team had updated the PR, please review it once again. Thanks in advance.

2021-08-11 17:19 UTC, lbalmaceda approved these changes
Apologies for the delayed review. I manually tested this and works as advertised 👍  Thanks for the contribution.

### Additional testing insight 
I added some log lines in different steps to check which alias was being used at each time. Some videos/screenshots I captured:

#### Using 1.23.0

https://user-images.githubusercontent.com/3900123/129072212-35def13b-ada3-4bd2-ae28-fa7bf1470953.mp4

#### Using this PR on next login

https://user-images.githubusercontent.com/3900123/129072281-d1d10d43-e175-4ee9-88eb-db43e2b6f4ca.mp4

Logs indicate that there was nothing stored with the "new alias" but everything proceeded fine after using the "old alias".

![migration-suceeded](https://user-images.githubusercontent.com/3900123/129072306-d422db1c-e50b-4320-8124-1f852ceb9373.png)

#### Using the PR after logging out


https://user-images.githubusercontent.com/3900123/129072450-f9e550c0-2587-4400-85f8-b2005568658e.mp4

As seen in the logs: the old Keystore entry still exists, same for the AES encrypted value. But the IV is not found and a new one is stored using the "new alias".

![migration-normal](https://user-images.githubusercontent.com/3900123/129072474-eb951300-8eca-4431-a1e7-fae7aca4bf53.png)


#### Using the PR in a fresh emulator
As seen in the logs: a new Keystore entry, AES, and IV are generated with "new aliases".

![migration-clean](https://user-images.githubusercontent.com/3900123/129073635-7850ef79-e86c-4839-9eb7-a186f9b75932.png)

2021-08-11 17:27 UTC, lbalmaceda commented
@Maksym-Motornyi I cannot rebase this PR nor push a rebase to this branch because I don't have permission. 

![image](https://user-images.githubusercontent.com/3900123/129075074-1c29ce6d-1f85-493e-bf73-e130237e85db.png)

You can either rebase and update the PR, so I can re-approve it. Or you can enable the "allow edits by maintainers" checkbox on the right of the PR. 
![image](https://user-images.githubusercontent.com/3900123/129075273-7318bd0d-4c90-497b-844b-1a42eea8507b.png)

2021-09-09 17:23 UTC, lbalmaceda commented
I'll have to close this due to inactivity. But I'll take your commits into a new PR that is rebased against the default branch. Thanks for your contribution @Maksym-Motornyi

2021-09-09 17:23 UTC, closed without merging